### ISSUE TITLE
Running under Windows 

### ISSUE THREAD

**Issue by rfvermut** [mumoshu/variant#67]
Can this be run under Windows or Cygwin?

```powershell
PS C:\Users\MyUser> go get -u github.com/mumoshu/variant
PS C:\Users\MyUser> variant version
panic: open .C:\Users\MyUser\go\bin\variant.exeenv: The filename, directory name, or volume label syntax is incorrect.

goroutine 1 [running]:
github.com/mumoshu/variant/pkg/run.RunTaskDef(0xc00008c030, 0x2a, 0xc0000b4b00, 0xc00005e410, 0x1, 0x1)
        C:/Users/MyUser/go/src/github.com/mumoshu/variant/pkg/run/run.go:121 +0x18d0
github.com/mumoshu/variant/pkg/run.Dev()
        C:/Users/MyUser/go/src/github.com/mumoshu/variant/pkg/run/run.go:95 +0x31f
main.main()
        C:/Users/MyUser/go/src/github.com/mumoshu/variant/main.go:8 +0x27
```

**Comment by mumoshu** [comment]
@rfvermut Hey! Not yet - but perhaps it would be a matter of replacing several `strings.Join` to `filepath.Join` in the code-base.

**Comment by rfvermut** [comment]
Looks like it was caused by https://github.com/golang/go/issues/7698
